events{

}

http{

      upstream backend {
        server gateway1:8000;
        server gateway2:8000;
      }    

      server{
        listen 80;
        location /{
            proxy_pass http://backend;
            # return 200 "hello from nginx";
        }
      } 
}