services:
   nginx:
    image: nginx
    ports:
      - 8000:80  
    # লোকাল মেশিনের কনফিগ ফাইলকে কন্টেইনারের কনফিগ ফাইলের সাথে বাইন্ড মাউন্ট করার জন্য
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
     
   server1:
    build: ./server
    env_file:
      - ./server/.env
    environment:
      - SERVER_NAME="1st server"
    ports:
      - 5001:7000  

   server2:
    build: ./server
    env_file:
      - ./server/.env
    environment:
      - SERVER_NAME="2nd server"  
    ports:
      - 5002:7000    

   server3:
    build: ./server
    env_file:
      - ./server/.env
    environment:
      - SERVER_NAME="3rd server"
    ports:
      - 5003:7000    